rm -rf /media/dgraper/PATRIOT/.Trash-1000
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/031822
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/031822.2
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/branches
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/hooks
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/info
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/logs
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/logs/refs
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/logs/refs/heads
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/logs/refs/remotes
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/logs/refs/remotes/origin
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/01
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/02
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/05
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/07
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/0e
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/10
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/12
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/15
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/16
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/1b
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/22
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/25
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/26
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/29
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/2c
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/2f
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/31
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/38
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/3a
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/44
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/4c
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/59
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/5e
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/63
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/67
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/68
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/72
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/73
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/74
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/78
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/7f
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/80
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/81
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/82
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/85
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/86
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/88
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/8a
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/8e
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/90
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/94
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/95
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/a2
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/a6
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/a7
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/a8
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/a9
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/ac
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/ad
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/b0
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/b3
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/b6
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/b7
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/bc
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/bf
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/c0
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/c1
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/c7
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/ca
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/cb
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/cc
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/ce
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/d0
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/d1
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/d8
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/d9
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/dd
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/e0
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/e2
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/e6
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/e9
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/ed
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/f2
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/f4
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/fa
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/info
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/objects/pack
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/refs
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/refs/heads
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/refs/remotes
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/refs/remotes/origin
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.git/refs/tags
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.idea
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.idea/inspectionProfiles
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.idea/shelf
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/backupExecution/.idea/shelf/Uncommitted_changes_before_Update_at_4_19_22,_3_55_PM_[Changes]
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/Fats\ Waller\ -\ Breakin\'\ The\ Ice
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/Fats\ Waller\ -\ Breakin\'\ The\ Ice/Disc\ 1
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/home
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/home/dgraper
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/home/dgraper/colossus_share0
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/home/dgraper/colossus_share0/4kvid
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/home/dgraper/colossus_share0/4kvid/031822
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/home/dgraper/colossus_share0/Audio0
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/home/dgraper/colossus_share0/Audio0/1920-30s\ Music
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/home/dgraper/colossus_share0/Audio0/1920-30s\ Music/1936\ A\ Time\ To\ Remember
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/home/dgraper/colossus_share0/Audio0/1920-30s\ Music/Fats\ Waller\ -\ Breakin\'\ The\ Ice
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/home/dgraper/colossus_share0/Audio0/1920-30s\ Music/Fats\ Waller\ -\ Breakin\'\ The\ Ice/Disc\ 1
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/home/dgraper/colossus_share0/Movies
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/home/dgraper/colossus_share0/Movies/The\ Best\ Man\ \(1964\)
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/.idea
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/.idea/inspectionProfiles
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/bin
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/_distutils_hack
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/_distutils_hack/__pycache__
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip-21.3.1.dist-info
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_internal
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_internal/cli
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_internal/commands
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_internal/distributions
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_internal/index
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_internal/locations
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_internal/metadata
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_internal/models
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_internal/network
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_internal/operations
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_internal/operations/build
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_internal/operations/install
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_internal/req
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_internal/resolution
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_internal/resolution/legacy
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_internal/utils
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_internal/vcs
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/cachecontrol
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/cachecontrol/caches
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/certifi
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/chardet
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/chardet/cli
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/chardet/metadata
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/colorama
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/distlib
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/distlib/_backport
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/html5lib
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/html5lib/filters
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/html5lib/treeadapters
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/html5lib/treebuilders
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/html5lib/treewalkers
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/html5lib/_trie
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/idna
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/msgpack
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/packaging
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/pep517
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/pkg_resources
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/platformdirs
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/progress
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/requests
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/resolvelib
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/resolvelib/compat
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/tenacity
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/tomli
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/urllib3
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/contrib
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/contrib/_securetransport
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/packages
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/packages/backports
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/packages/ssl_match_hostname
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/urllib3/util
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pip/_vendor/webencodings
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pkg_resources
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pkg_resources/extern
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pkg_resources/tests
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pkg_resources/tests/data
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pkg_resources/tests/data/my-test-package-source
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pkg_resources/_vendor
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/pkg_resources/_vendor/packaging
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/__pycache__
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/setuptools
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/setuptools-60.2.0.dist-info
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/setuptools/command
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/setuptools/_distutils
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/setuptools/_distutils/command
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/setuptools/extern
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/setuptools/_vendor
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/setuptools/_vendor/more_itertools
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/setuptools/_vendor/packaging
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/wheel
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/wheel-0.37.1.dist-info
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/wheel/cli
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/wheel/vendored
rm -rf /media/dgraper/PATRIOT/.Trash-1000/files/pythonProject/venv/lib/python3.8/site-packages/wheel/vendored/packaging
rm -rf /media/dgraper/PATRIOT/.Trash-1000/info
